# amvera.yml

meta:
    # The name of your overall project in the Amvera dashboard
    app: my-bot-project

services:
    # --- Service 1: Your PostgreSQL Database ---
    # This defines the service. Let's call it 'my-db'
    amvera-dambosin-cnpg-horoscope-bot-db-rw:
        type: postgres
        version: 17.5

tasks:
    # --- Task 1: Your Bot Application ---
    # This defines your application code. Let's call it 'my-bot'
    my-bot:
        type: node

        # --- The Build Process ---
        build:
            # 1. Install all npm packages
            - npm install
            # 2. Generate the Prisma Client
            - npx prisma generate
            # 3. Compile TypeScript to JavaScript (runs 'tsc')
            - npm run build
            # 4. Run migrations on the Amvera database
            - npx prisma migrate deploy

        # --- The Run Command ---
        run:
            # This runs your 'start' script from package.json
            - npm start

        # --- The CRITICAL Part: Connecting DB to Bot ---
        env:
            imports:
                # This tells Amvera: "Find the service named 'my-db'
                # and inject its 'DATABASE_URL' as an environment variable
                # into this task."
                - service: amvera-dambosin-cnpg-horoscope-bot-db-rw
                  variables: [DATABASE_URL]
